# Generated by Django 3.2.11 on 2022-01-13 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('[ㄱ-힣]', message='한글을 입력해주세요.')])),
                ('foreign_name', models.CharField(blank=True, max_length=100)),
                ('rating', models.CharField(choices=[('S', 'S-class'), ('A', 'A-class'), ('B', 'B-class'), ('C', 'C-class'), ('L', 'L-class')], max_length=1)),
                ('pet', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
